### ISSUE TITLE
Editing round start/end time returns wrong time

### ISSUE THREAD

**Issue by Maritsu** [varqox/sim-project#24]
Trying to edit a round's start or end time (full result time / ranking time might be affected, too) result in the wrong time being set.

Example:
- trying to set (correct) start/end time of [Round 1485](https://sim.13lo.pl/c/r1485)  
![image](https://github.com/varqox/sim-project/assets/66056347/ef102ad6-603e-4dc3-83c3-7989915fb3f1) ![image](https://github.com/varqox/sim-project/assets/66056347/ec0a3dba-dbe8-433e-b601-21fe6a724996)  

- resulting time is in the year 2078  
![image](https://github.com/varqox/sim-project/assets/66056347/819eb381-efdf-4fb2-897a-673dd812065c)

I've asked around, and the issue might stem from this line: https://github.com/varqox/sim-project/blob/640c701acf116decfc9de09f93a77f14f1d6af3e/subprojects/sim/include/sim/inf_datetime.hh#L161 or at least from [`640c701` / the commit which last edited this line](https://github.com/varqox/sim-project/commit/640c701acf116decfc9de09f93a77f14f1d6af3e).

**Comment by varqox** [comment]
Thanks for reporting the issue!
The line and commit you mentioned were the culprit. It should be fixed now by 6f4f81d25697f05781419d384e26344bac2b6f75.
