### ISSUE TITLE
Compiling latex with sip doc doesn't produce correct line numbering.

### ISSUE THREAD

**Issue by Bombylius** [varqox/sim-project#29]
When I compile a statement with multiple pages with `sip doc` I get page numbers like `1/??`. Example file:
```latex
\documentclass[pl]{sim-statement}

\problemName{}
\memoryLimit{512 MiB}
\additionalFooterInfo{}
\contestName{}
\date{}

\begin{document}
\begin{statement}
xd
\newpage
xd

\end{statement}
\end{document}
```

When I compile it myself by running `pdflatex` twice the page numbering works. I suspect that with `sip doc` `pdflatex` doesn't have access to the necessary intermediate files during the second run.

**Comment by varqox** [comment]
Thanks for reporting.

Fixed in fba8a658f15666e048db47f6b0c1b3c9a42b9a26
